### ISSUE TITLE
Bug id #2 [opencv_dnn] is not reproduced.

### ISSUE THREAD

**Issue by sporsho** [tum-i22/CBugPP#1]
Even after adding the buggy code in Torch_importer.cpp, the test case Torch_Importer.net_non_spatial passes. 
![bug2](https://user-images.githubusercontent.com/13591451/35291521-cd2eb98e-006d-11e8-8b10-c396a55660a7.png)

**Comment by rezaurrakib** [comment]
Please build in release mode.
